const KEY='studyQuest.v1.decks';
const SAMPLE={format:'StudyCards',version:'1.0',title:'Science Sample — Plants',subject:'Science',cards:[
{id:'s1',type:'multiple_choice',question:'What process do plants use to make food?',choices:['Respiration','Photosynthesis','Digestion','Germination'],answer:'Photosynthesis'},
{id:'s2',type:'written',question:'What gas do plants take in during photosynthesis?',answer:'Carbon dioxide.'},
{id:'s3',type:'true_false',question:'Plants need sunlight to carry out photosynthesis.',answer:'True'}]};
let decks=load(); let route='home'; let currentDeck=null; let studyIndex=0; let flipped=false; let session={known:0,missed:0,results:{}};
const app=document.getElementById('app'), fileInput=document.getElementById('fileInput'), toast=document.getElementById('toast');
function load(){try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch{return[]}}
function save(){localStorage.setItem(KEY,JSON.stringify(decks))}
function id(){return Math.random().toString(36).slice(2,10)}
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function nav(r){route=r; render(); window.scrollTo({top:0,behavior:'smooth'})}
function toastMsg(s){toast.textContent=s;gsap.to(toast,{autoAlpha:1,y:0,duration:.2});gsap.to(toast,{autoAlpha:0,y:10,delay:2.2,duration:.3})}
function render(){if(route==='home')home(); if(route==='decks')deckList(); if(route==='import')importPage(); if(route==='review')reviewPage(); if(route==='study')studyPage();}
document.addEventListener('click',e=>{const n=e.target.closest('[data-nav]');if(n)nav(n.dataset.nav)});
function home(){app.innerHTML=`<div class="shell"><section class="hero"><div><div class="eyebrow">AI-assisted • Private • No API required</div><h1>Turn schoolwork into <span>Study Quests.</span></h1><p>Use ChatGPT to read practice-test photos, then bring the structured cards here. Study Quest handles validation, flashcards, progress, and review entirely in your browser.</p><div class="actions"><button class="primary" data-nav="import">＋ Create a Deck</button><button class="secondary" data-nav="decks">Open My Decks</button></div></div><div class="orb-card"><div class="ring"></div><div class="orb"></div></div></section><section><div class="section-title"><h2>How it works</h2></div><div class="grid"><div class="panel"><b>01 · Photograph</b><p class="muted">Take pictures of every page of the practice test.</p></div><div class="panel"><b>02 · Ask ChatGPT</b><p class="muted">Use the included import template with your images.</p></div><div class="panel"><b>03 · Validate</b><p class="muted">Import the StudyCards file and quickly correct anything ChatGPT misunderstood.</p></div><div class="panel"><b>04 · Study</b><p class="muted">Flip cards, mark what you knew, and review missed cards.</p></div></div></section><p class="footer-note">Your decks stay in this browser. Study Quest does not send your schoolwork anywhere.</p></div>`; animateIn()}
function deckList(){app.innerHTML=`<div class="shell"><div class="section-title"><div><div class="eyebrow">Your library</div><h1>My Decks</h1></div><button class="primary" data-nav="import">＋ New Deck</button></div>${decks.length?`<div class="grid">${decks.map(d=>`<article class="deck-card"><div><span class="pill">${esc(d.subject||'Study')}</span><h3 class="deck-title">${esc(d.title)}</h3><p class="muted">${d.cards.length} cards</p></div><div class="actions"><button class="primary" data-open="${d.id}">Study</button><button class="secondary" data-edit="${d.id}">Review</button></div></article>`).join('')}</div>`:`<div class="panel empty"><div class="big-score">✦</div><h2>No decks yet</h2><p class="muted">Create your first deck from a practice test.</p><button class="primary" data-nav="import">Create a Deck</button></div>`}</div>`;document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>startStudy(b.dataset.open));document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>{currentDeck=decks.find(x=>x.id===b.dataset.edit);route='review';render()});animateIn()}
function importPage(){app.innerHTML=`<div class="shell"><div class="section-title"><div><div class="eyebrow">New deck</div><h1>Import StudyCards</h1></div></div><div class="grid"><div class="panel"><h2>Option A — Import a JSON file</h2><p class="muted">Ask ChatGPT to use the included template, then save its JSON output as a <b>.json</b> file.</p><div class="drop" id="drop"><b>Drop StudyCards JSON here</b><p class="muted small">or</p><button class="secondary" id="browse">Choose File</button></div><div class="actions"><button class="secondary" id="sample">Load Sample Deck</button><button class="ghost" id="template">Copy ChatGPT Template</button></div></div><div class="panel"><h2>Option B — Paste JSON</h2><textarea id="json" placeholder='Paste the JSON object returned by ChatGPT here…'></textarea><div class="actions"><button class="primary" id="parse">Validate & Continue</button></div><p class="footer-note">No API key is used. ChatGPT does the image understanding; this app only processes the structured result.</p></div></div></div>`;setupImport();animateIn()}
function setupImport(){const drop=document.getElementById('drop');document.getElementById('browse').onclick=()=>fileInput.click();document.getElementById('sample').onclick=()=>acceptDeck(SAMPLE);document.getElementById('parse').onclick=()=>{try{acceptDeck(JSON.parse(document.getElementById('json').value))}catch(e){toastMsg('That JSON could not be parsed.')}};document.getElementById('template').onclick=copyTemplate;['dragenter','dragover'].forEach(x=>drop.addEventListener(x,e=>{e.preventDefault();drop.classList.add('drag')}));['dragleave','drop'].forEach(x=>drop.addEventListener(x,e=>{e.preventDefault();drop.classList.remove('drag')}));drop.addEventListener('drop',e=>readFile(e.dataTransfer.files[0]));fileInput.onchange=()=>readFile(fileInput.files[0])}
async function readFile(f){if(!f)return;try{const obj=JSON.parse(await f.text());acceptDeck(obj)}catch{toastMsg('Please choose a valid StudyCards JSON file.')}}
function normalize(raw){if(!raw||raw.format!=='StudyCards'||!Array.isArray(raw.cards))throw Error('Invalid StudyCards format');return {id:id(),title:raw.title||'Untitled Study Deck',subject:raw.subject||'Study',created:new Date().toISOString(),cards:raw.cards.map((c,i)=>({id:c.id||id(),type:c.type||'written',question:String(c.question||''),choices:Array.isArray(c.choices)?c.choices.map(String):[],answer:String(c.answer||''),pairs:Array.isArray(c.pairs)?c.pairs:[]}))}}
function acceptDeck(raw){try{currentDeck=normalize(raw);route='review';render()}catch{toastMsg('This does not look like a StudyCards 1.0 deck. Use the supplied ChatGPT template.')}}
function reviewPage(){if(!currentDeck)return nav('import');app.innerHTML=`<div class="shell"><div class="section-title"><div><div class="eyebrow">Validation</div><h1>${esc(currentDeck.title)}</h1><p class="muted">${currentDeck.cards.length} cards • Check the answers before studying.</p></div><button class="secondary" data-nav="import">Cancel</button></div><div class="panel"><div class="statbar"><div class="stat"><span class="muted">Cards</span><b>${currentDeck.cards.length}</b></div><div class="stat"><span class="muted">Multiple choice</span><b>${currentDeck.cards.filter(c=>c.type==='multiple_choice').length}</b></div><div class="stat"><span class="muted">Written / other</span><b>${currentDeck.cards.filter(c=>c.type!=='multiple_choice').length}</b></div></div><div class="review-list">${currentDeck.cards.map((c,i)=>cardEditor(c,i)).join('')}</div><div class="actions"><button class="primary" id="saveDeck">Save & Study</button><button class="secondary" id="exportDeck">Export JSON</button></div></div></div>`;document.querySelectorAll('[data-save-card]').forEach(b=>b.onclick=()=>updateCard(b.dataset.saveCard));document.getElementById('saveDeck').onclick=saveCurrent;document.getElementById('exportDeck').onclick=exportCurrent;animateIn()}
function cardEditor(c,i){return `<div class="review-item"><div class="review-head"><b>${String(i+1).padStart(2,'0')} · ${esc(c.type.replace('_',' '))}</b><span class="pill">Card ${i+1}</span></div><div class="edit-grid"><label>Question<textarea data-q="${c.id}">${esc(c.question)}</textarea></label><label>Correct answer<textarea data-a="${c.id}">${esc(c.answer)}</textarea></label></div>${c.type==='multiple_choice'?`<label class="small">Choices${c.choices.map((x,j)=>`<div class="choice-row"><input data-c="${c.id}" data-j="${j}" value="${esc(x)}"><button class="ghost" data-remove-choice="${c.id}" data-j="${j}">×</button></div>`).join('')}<button class="ghost" data-add-choice="${c.id}">＋ Add choice</button></label>`:''}</div>`}
document.addEventListener('click',e=>{const add=e.target.closest('[data-add-choice]');if(add){const c=currentDeck.cards.find(x=>x.id===add.dataset.addChoice);c.choices.push('');reviewPage()}const rem=e.target.closest('[data-remove-choice]');if(rem){const c=currentDeck.cards.find(x=>x.id===rem.dataset.removeChoice);c.choices.splice(+rem.dataset.j,1);reviewPage()}});
function updateCard(cardId){const c=currentDeck.cards.find(x=>x.id===cardId);c.question=document.querySelector(`[data-q="${cardId}"]`).value;c.answer=document.querySelector(`[data-a="${cardId}"]`).value;document.querySelectorAll(`[data-c="${cardId}"]`).forEach((el,j)=>c.choices[j]=el.value)}
function saveCurrent(){currentDeck.cards.forEach(c=>updateCard(c.id));const idx=decks.findIndex(d=>d.id===currentDeck.id);if(idx>=0)decks[idx]=currentDeck;else decks.unshift(currentDeck);save();toastMsg('Deck saved.');setTimeout(()=>startStudy(currentDeck.id),250)}
function exportCurrent(){currentDeck.cards.forEach(c=>updateCard(c.id));const raw={format:'StudyCards',version:'1.0',title:currentDeck.title,subject:currentDeck.subject,cards:currentDeck.cards.map(({id,type,question,choices,answer,pairs})=>({id,type,question,choices,answer,pairs}))};download(`${currentDeck.title.replace(/[^a-z0-9]+/gi,'-').toLowerCase()}.json`,JSON.stringify(raw,null,2))}
function download(name,text){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'application/json'}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
function startStudy(id0){currentDeck=decks.find(d=>d.id===id0);if(!currentDeck)return;studyIndex=0;flipped=false;session={known:0,missed:0,results:{}};route='study';render()}
function studyPage(){if(!currentDeck)return nav('decks');if(studyIndex>=currentDeck.cards.length)return finishPage();const c=currentDeck.cards[studyIndex];app.innerHTML=`<div class="shell study-wrap"><div class="study-card ${flipped?'flipped':''}" id="studyCard"><div class="card-face"><div class="pill">${studyIndex+1} / ${currentDeck.cards.length} · ${esc(c.type.replace('_',' '))}</div><div class="question"><h2>${esc(c.question)}</h2>${c.type==='multiple_choice'?`<div class="choices">${c.choices.map(x=>`<div class="choice">${esc(x)}</div>`).join('')}</div>`:''}<div class="actions"><button class="primary" id="flip">↻ Reveal Answer</button></div></div><div class="answer"><div class="eyebrow">Answer</div><h2>${esc(c.answer)}</h2>${c.type==='matching'&&c.pairs?.length?`<div class="choices">${c.pairs.map(p=>`<div class="choice">${esc(p.left)} → ${esc(p.right)}</div>`).join('')}</div>`:''}<div class="study-controls"><button class="danger" id="miss">✕ I missed it</button><button class="primary" id="know">✓ I knew it</button></div></div></div><div class="progress"><i style="width:${studyIndex/currentDeck.cards.length*100}%"></i></div><div class="study-controls"><button class="ghost" id="quit">Exit</button><button class="ghost" id="skip">Skip</button></div></div></div>`;document.getElementById('flip').onclick=()=>{flipped=true;render()};document.getElementById('know').onclick=()=>rate(true);document.getElementById('miss').onclick=()=>rate(false);document.getElementById('skip').onclick=()=>{studyIndex++;flipped=false;render()};document.getElementById('quit').onclick=()=>nav('decks');animateIn()}
function rate(ok){session.results[currentDeck.cards[studyIndex].id]=ok;ok?session.known++:session.missed++;studyIndex++;flipped=false;render()}
function finishPage(){app.innerHTML=`<div class="shell"><div class="panel center" style="margin-top:100px"><div class="big-score">${session.known}/${currentDeck.cards.length}</div><h1>Quest complete!</h1><p class="muted">${session.missed?`${session.missed} card${session.missed===1?'':'s'} need another look.`:'You knew every card you rated!'}</p><div class="actions" style="justify-content:center">${session.missed?`<button class="primary" id="reviewMissed">Review Missed</button>`:''}<button class="secondary" data-nav="decks">Back to Decks</button></div></div></div>`;if(document.getElementById('reviewMissed'))document.getElementById('reviewMissed').onclick=()=>{currentDeck={...currentDeck,cards:currentDeck.cards.filter(c=>session.results[c.id]===false)};studyIndex=0;flipped=false;session.known=0;session.missed=0;route='study';render()};animateIn()}
function animateIn(){if(window.gsap)gsap.from('#app .panel,#app .deck-card,#app .hero > *',{opacity:0,y:14,stagger:.04,duration:.45,ease:'power2.out'})}
async function copyTemplate(){try{const t=await fetch('templates/chatgpt-import-template.md').then(r=>r.text());await navigator.clipboard.writeText(t);toastMsg('ChatGPT import template copied.')}catch{toastMsg('Open templates/chatgpt-import-template.md to copy the template.')}}
// Lightweight particle background — no Three.js required for the core app; the visual layer remains dependency-light.
const cv=document.getElementById('space'),ctx=cv.getContext('2d');let dots=[];function resize(){cv.width=innerWidth*devicePixelRatio;cv.height=innerHeight*devicePixelRatio;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);dots=Array.from({length:Math.min(90,Math.floor(innerWidth/15))},()=>({x:Math.random()*innerWidth,y:Math.random()*innerHeight,r:Math.random()*1.4+.3,v:Math.random()*.15+.03}))}function particles(){ctx.clearRect(0,0,innerWidth,innerHeight);ctx.fillStyle='rgba(255,255,255,.45)';dots.forEach(d=>{d.y-=d.v;if(d.y<0)d.y=innerHeight;ctx.beginPath();ctx.arc(d.x,d.y,d.r,0,Math.PI*2);ctx.fill()});requestAnimationFrame(particles)}addEventListener('resize',resize);resize();particles();render();
