const APP_VERSION='1.3.0';
const STUDYCARDS_VERSION='1.2';
const KEY='studyQuest.v2.decks';
const LEGACY_KEY='studyQuest.v1.decks';
const SAMPLE={format:'StudyCards',version:STUDYCARDS_VERSION,title:'Science Sample — Plants',subject:'Science',cards:[
{id:'s1',type:'multiple_choice',question:'What process do plants use to make food?',choices:['Respiration','Photosynthesis','Digestion','Germination'],answer:'Photosynthesis',answer_source:'source'},
{id:'s2',type:'written',question:'What gas do plants take in during photosynthesis?',answer:'Carbon dioxide.',answer_source:'source'},
{id:'s3',type:'true_false',question:'Plants need sunlight to carry out photosynthesis.',answer:'True',answer_source:'source'}]};
let decks=load();
let route='home';
let currentDeck=null;
let studyIndex=0;
let activeCardIds=null;
let flipped=false;
let quizMode=false;
let quizAnswered=false;
let quizGiven=null;
let matchingSelections={};
let session={known:0,missed:0,results:{}};
const app=document.getElementById('app'),fileInput=document.getElementById('fileInput'),toast=document.getElementById('toast');

function load(){try{const raw=localStorage.getItem(KEY)??localStorage.getItem(LEGACY_KEY)??'[]';return JSON.parse(raw).map(migrateDeck)}catch{return[]}}
function save(){localStorage.setItem(KEY,JSON.stringify(decks))}
function id(){return Math.random().toString(36).slice(2,10)}
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function nav(r){route=r;render();window.scrollTo({top:0,behavior:'smooth'})}
function toastMsg(s){toast.textContent=s;gsap.to(toast,{autoAlpha:1,y:0,duration:.2});gsap.to(toast,{autoAlpha:0,y:10,delay:2.2,duration:.3})}
function render(){if(route==='home')home();if(route==='decks')deckList();if(route==='import')importPage();if(route==='validation')validationPage();if(route==='study')studyPage();if(route==='quiz')quizPage();}
document.addEventListener('click',e=>{const n=e.target.closest('[data-nav]');if(n)nav(n.dataset.nav)});

function home(){app.innerHTML=`<div class="shell"><section class="hero"><div><div class="eyebrow">AI-assisted • Private • No API required</div><h1>Turn schoolwork into <span>Study Quests.</span></h1><p>Use ChatGPT to read practice-test photos, then bring the structured cards here. Study Quest handles validation, flashcards, quizzes, progress, and review entirely in your browser.</p><div class="actions"><button class="primary" data-nav="import">＋ Create a Deck</button><button class="secondary" data-nav="decks">Open My Decks</button></div></div><div class="orb-card"><div class="ring"></div><div class="orb"></div></div></section><section><div class="section-title"><h2>How it works</h2></div><div class="grid"><div class="panel"><b>01 · Photograph</b><p class="muted">Take pictures of every page of the practice test.</p></div><div class="panel"><b>02 · Ask ChatGPT</b><p class="muted">Use the included import template with your images.</p></div><div class="panel"><b>03 · Validate</b><p class="muted">Review the extracted cards and correct anything ChatGPT misunderstood.</p></div><div class="panel"><b>04 · Study & Quiz</b><p class="muted">Practice recall, test yourself, and review missed cards.</p></div></div></section><p class="footer-note">Your decks stay in this browser. Study Quest does not send your schoolwork anywhere. · v${APP_VERSION}</p></div>`;animateIn()}

function deckStats(d){const p=d.progress||{};const total=d.cards.length||1;const mastered=new Set(p.masteredIds||[]).size;const missed=new Set(p.missedIds||[]).size;return {sessions:p.sessions||0,mastered,missed,percent:Math.round(mastered/total*100)}}
function deckList(){app.innerHTML=`<div class="shell"><div class="section-title"><div><div class="eyebrow">Your library</div><h1>My Decks</h1></div><button class="primary" data-nav="import">＋ New Deck</button></div>${decks.length?`<div class="grid">${decks.map(d=>{const s=deckStats(d);return `<article class="deck-card"><div><span class="pill">${esc(d.subject||'Study')}</span><h3 class="deck-title">${esc(d.title)}</h3><p class="muted">${d.cards.length} cards</p><div class="mini-progress"><i style="width:${s.percent}%"></i></div><div class="deck-meta"><span>${s.sessions} study session${s.sessions===1?'':'s'}</span><span>${s.mastered}/${d.cards.length} mastered</span></div>${s.missed?`<p class="missed-note">${s.missed} card${s.missed===1?'':'s'} marked for review</p>`:''}</div><div class="actions"><button class="primary" data-study="${d.id}">🧠 Study</button><button class="secondary" data-quiz="${d.id}">📝 Quiz</button>${s.missed?`<button class="ghost" data-review="${d.id}">🔄 Review Missed</button>`:''}<button class="ghost" data-validation="${d.id}">🔎 Validation Review</button><button class="danger-outline" data-delete="${d.id}">🗑 Delete</button></div></article>`}).join('')}</div>`:`<div class="panel empty"><div class="big-score">✦</div><h2>No decks yet</h2><p class="muted">Create your first deck from a practice test.</p><button class="primary" data-nav="import">Create a Deck</button></div>`}</div>`;
document.querySelectorAll('[data-study]').forEach(b=>b.onclick=()=>startSession(b.dataset.study,false));
document.querySelectorAll('[data-quiz]').forEach(b=>b.onclick=()=>startSession(b.dataset.quiz,true));
document.querySelectorAll('[data-review]').forEach(b=>b.onclick=()=>startMissed(b.dataset.review));
document.querySelectorAll('[data-validation]').forEach(b=>b.onclick=()=>{currentDeck=decks.find(x=>x.id===b.dataset.validation);activeCardIds=null;route='validation';render()});
document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>confirmDelete(b.dataset.delete));
animateIn()}
function confirmDelete(deckId){const d=decks.find(x=>x.id===deckId);if(!d)return;const ok=window.confirm(`Delete “${d.title}”?\n\nThis removes the deck and its saved study progress from this browser. An exported .studyquest.json file will not be affected.`);if(!ok)return;decks=decks.filter(x=>x.id!==deckId);save();if(currentDeck?.id===deckId){currentDeck=null;activeCardIds=null;route='decks'}toastMsg('Deck deleted.');render()}

function importPage(){app.innerHTML=`<div class="shell"><div class="section-title"><div><div class="eyebrow">New deck</div><h1>Turn a practice test into cards</h1><p class="muted">Study Quest uses ChatGPT for image understanding, then keeps the rest of the process in your browser.</p></div></div><div class="import-flow"><section class="panel step-panel"><div class="step-number">01</div><div><div class="eyebrow">Get your questions from ChatGPT</div><h2>Use the Study Quest template</h2><p class="muted">Copy the template below, start a new ChatGPT conversation, attach one or more photos of the practice test, and paste the template into your message.</p><div class="actions"><button class="primary" id="template">📋 Copy ChatGPT Import Template</button><button class="secondary" id="openChatGPT">Open ChatGPT ↗</button></div><p class="helper">The template tells ChatGPT to read every page, preserve multiple-choice choices, identify the answer source, and return StudyCards JSON.</p></div></section><section class="panel step-panel"><div class="step-number">02</div><div class="full-width"><div class="eyebrow">Bring the cards back here</div><h2>Paste ChatGPT's JSON response</h2><p class="muted">You do <b>not</b> need to save a file. Just copy ChatGPT's JSON response and paste it below.</p><textarea id="json" class="json-box" placeholder='Paste the JSON object returned by ChatGPT here…'></textarea><div class="actions"><button class="primary" id="parse">✓ Validate & Continue</button></div></div></section></div><details class="advanced-import"><summary>Advanced: import a saved StudyCards JSON file</summary><div class="panel"><p class="muted">If you already saved a StudyCards JSON file, you can import it directly.</p><div class="drop" id="drop"><b>Drop StudyCards JSON here</b><p class="muted small">or</p><button class="secondary" id="browse">Choose File</button></div><div class="actions"><button class="secondary" id="sample">Load Sample Deck</button></div></div></details><p class="footer-note">🔒 No API key is used. Your practice-test images stay in your ChatGPT conversation; Study Quest only receives the structured result you paste or import.</p></div><div id="templateFallback" class="modal-backdrop" hidden><div class="modal panel"><div class="section-title"><div><div class="eyebrow">Clipboard fallback</div><h2>Copy the template below</h2></div><button class="ghost" id="closeFallback">Close</button></div><textarea id="templateText" class="template-box" readonly></textarea><div class="actions"><button class="primary" id="selectTemplate">Select All Template Text</button></div></div></div>`;setupImport();animateIn()}
function setupImport(){const drop=document.getElementById('drop');if(document.getElementById('browse'))document.getElementById('browse').onclick=()=>fileInput.click();if(document.getElementById('sample'))document.getElementById('sample').onclick=()=>acceptDeck(SAMPLE);document.getElementById('parse').onclick=()=>{try{acceptDeck(JSON.parse(stripFences(document.getElementById('json').value)))}catch(e){toastMsg('That JSON could not be parsed.')}};document.getElementById('template').onclick=copyTemplate;const chat=document.getElementById('openChatGPT');if(chat)chat.onclick=()=>window.open('https://chatgpt.com/','_blank','noopener');if(drop){['dragenter','dragover'].forEach(x=>drop.addEventListener(x,e=>{e.preventDefault();drop.classList.add('drag')}));['dragleave','drop'].forEach(x=>drop.addEventListener(x,e=>{e.preventDefault();drop.classList.remove('drag')}));drop.addEventListener('drop',e=>readFile(e.dataTransfer.files[0]))}fileInput.onchange=()=>readFile(fileInput.files[0]);const close=document.getElementById('closeFallback');if(close)close.onclick=()=>document.getElementById('templateFallback').hidden=true;const select=document.getElementById('selectTemplate');if(select)select.onclick=()=>{const t=document.getElementById('templateText');t.focus();t.select();toastMsg('Template selected — use Copy in your browser if needed.')}}
function stripFences(s){return s.trim().replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,'').trim()}
async function readFile(f){if(!f)return;try{const obj=JSON.parse(await f.text());acceptDeck(obj)}catch{toastMsg('Please choose a valid StudyCards JSON file.')}}

function migrateDeck(d){if(!d.progress)d.progress={sessions:0,masteredIds:[],missedIds:[]};d.cards=(d.cards||[]).map(c=>({...c,id:c.id||id(),choices:Array.isArray(c.choices)?c.choices:[],pairs:Array.isArray(c.pairs)?c.pairs:[],answer_source:c.answer_source||'unknown',verification:c.verification||'needs_review',notes:c.notes||''}));return d}
function normalize(raw){if(!raw||raw.format!=='StudyCards'||!Array.isArray(raw.cards))throw Error('Invalid StudyCards format');return {id:id(),title:raw.title||'Untitled Study Deck',subject:raw.subject||'Study',created:new Date().toISOString(),progress:raw.progress||{sessions:0,masteredIds:[],missedIds:[]},cards:raw.cards.map(c=>({id:c.id||id(),type:c.type||'written',question:String(c.question||''),choices:Array.isArray(c.choices)?c.choices.map(String):[],answer:String(c.answer||''),pairs:Array.isArray(c.pairs)?c.pairs.map(p=>({left:String(p.left||''),right:String(p.right||'')})):[],answer_source:c.answer_source||'unknown',verification:c.verification||'needs_review',notes:c.notes||''}))}}
function acceptDeck(raw){try{currentDeck=normalize(raw);activeCardIds=null;route='validation';render()}catch{toastMsg('This does not look like a StudyCards deck. Use the supplied ChatGPT template.')}}
function sourceLabel(s){return ({source:'Found in source',student:'Student response',teacher_key:'Teacher / answer key',inferred:'AI-inferred',unknown:'Source not specified'})[s]||'Source not specified'}
function verificationLabel(v){return ({verified:'Verified',needs_review:'Needs review',unverified:'Unverified'})[v]||'Needs review'}
function validationPage(){if(!currentDeck)return nav('import');const counts={mc:currentDeck.cards.filter(c=>c.type==='multiple_choice').length,matching:currentDeck.cards.filter(c=>c.type==='matching').length,written:currentDeck.cards.filter(c=>c.type==='written').length,other:currentDeck.cards.filter(c=>!['multiple_choice','matching','written'].includes(c.type)).length};app.innerHTML=`<div class="shell"><div class="section-title"><div><div class="eyebrow">Validation Review</div><h1>${esc(currentDeck.title)}</h1><p class="muted">${currentDeck.cards.length} cards • Scan the answers, then expand any card you want to edit.</p></div><button class="secondary" data-nav="import">Cancel</button></div><div class="panel"><div class="statbar"><div class="stat"><span class="muted">Cards</span><b>${currentDeck.cards.length}</b></div><div class="stat"><span class="muted">Multiple choice</span><b>${counts.mc}</b></div><div class="stat"><span class="muted">Matching</span><b>${counts.matching}</b></div><div class="stat"><span class="muted">Written</span><b>${counts.written}</b></div></div><div class="validation-summary">${currentDeck.cards.map((c,i)=>summaryRow(c,i)).join('')}</div><div class="review-list compact-editors">${currentDeck.cards.map((c,i)=>cardEditor(c,i)).join('')}</div><div class="actions sticky-actions"><button class="primary" id="saveDeck">💾 Save & Study</button><button class="secondary" id="exportDeck">📤 Export Deck</button></div></div></div>`;wireEditors();document.getElementById('saveDeck').onclick=saveCurrent;document.getElementById('exportDeck').onclick=exportCurrent;animateIn()}
function summaryRow(c,i){const flagged=c.verification!=='verified'||c.answer_source==='inferred'||c.answer_source==='unknown';let ans=c.type==='matching'?`${c.pairs.length} pairs`:c.answer;return `<button class="summary-row ${flagged?'flagged':''}" data-jump="${c.id}"><span class="summary-num">${String(i+1).padStart(2,'0')}</span><span class="summary-type">${esc(c.type.replace('_',' '))}</span><span class="summary-question">${esc(c.question)}</span><span class="summary-answer">${esc(ans||'—')}</span><span class="summary-source">${c.verification!=='verified'?'⚠ ':''}${esc(sourceLabel(c.answer_source))} · ${esc(verificationLabel(c.verification))}</span><span class="summary-edit">Edit ›</span></button>`}
function cardEditor(c,i){return `<details class="review-item" id="editor-${c.id}"><summary class="review-head"><b>${String(i+1).padStart(2,'0')} · ${esc(c.type.replace('_',' '))}</b><span class="pill">Card ${i+1}</span></summary><div class="editor-body"><div class="edit-grid"><label>Question<textarea data-q="${c.id}">${esc(c.question)}</textarea></label><label>Answer<textarea data-a="${c.id}">${esc(c.answer)}</textarea></label></div>${c.type==='multiple_choice'?`<label class="small">Choices${c.choices.map((x,j)=>`<div class="choice-row"><input data-c="${c.id}" data-j="${j}" value="${esc(x)}"><button class="ghost" data-remove-choice="${c.id}" data-j="${j}">×</button></div>`).join('')}<button class="ghost" data-add-choice="${c.id}">＋ Add choice</button></label>`:''}${c.type==='matching'?`<div class="matching-editor"><label>Matching pairs</label>${c.pairs.map((p,j)=>`<div class="pair-row"><input data-pair-left="${c.id}" data-j="${j}" value="${esc(p.left)}"><span>→</span><input data-pair-right="${c.id}" data-j="${j}" value="${esc(p.right)}"><button class="ghost" data-remove-pair="${c.id}" data-j="${j}">×</button></div>`).join('')}<button class="ghost" data-add-pair="${c.id}">＋ Add pair</button></div>`:''}<div class="edit-grid meta-grid"><label>Answer source<select data-source="${c.id}">${['source','student','teacher_key','inferred','unknown'].map(x=>`<option value="${x}" ${c.answer_source===x?'selected':''}>${sourceLabel(x)}</option>`).join('')}</select></label><label>Verification<select data-verification="${c.id}">${['verified','needs_review','unverified'].map(x=>`<option value="${x}" ${c.verification===x?'selected':''}>${verificationLabel(x)}</option>`).join('')}</select></label><label>Notes<textarea data-notes="${c.id}" placeholder="Optional note for validation…">${esc(c.notes)}</textarea></label></div></div></details>`}
function wireEditors(){document.querySelectorAll('[data-jump]').forEach(b=>b.onclick=()=>{const d=document.getElementById('editor-'+b.dataset.jump);if(d){d.open=true;d.scrollIntoView({behavior:'smooth',block:'center'})}});document.querySelectorAll('[data-add-choice]').forEach(b=>b.onclick=()=>{syncAllEditors();const c=currentDeck.cards.find(x=>x.id===b.dataset.addChoice);c.choices.push('');validationPage()});document.querySelectorAll('[data-remove-choice]').forEach(b=>b.onclick=()=>{syncAllEditors();const c=currentDeck.cards.find(x=>x.id===b.dataset.removeChoice);c.choices.splice(+b.dataset.j,1);validationPage()});document.querySelectorAll('[data-add-pair]').forEach(b=>b.onclick=()=>{syncAllEditors();const c=currentDeck.cards.find(x=>x.id===b.dataset.addPair);c.pairs.push({left:'',right:''});validationPage()});document.querySelectorAll('[data-remove-pair]').forEach(b=>b.onclick=()=>{syncAllEditors();const c=currentDeck.cards.find(x=>x.id===b.dataset.removePair);c.pairs.splice(+b.dataset.j,1);validationPage()})}
function syncAllEditors(){currentDeck.cards.forEach(c=>{const q=document.querySelector(`[data-q="${c.id}"]`),a=document.querySelector(`[data-a="${c.id}"]`);if(q)c.question=q.value;if(a)c.answer=a.value;document.querySelectorAll(`[data-c="${c.id}"]`).forEach((el,j)=>c.choices[j]=el.value);document.querySelectorAll(`[data-pair-left="${c.id}"]`).forEach((el,j)=>c.pairs[j].left=el.value);document.querySelectorAll(`[data-pair-right="${c.id}"]`).forEach((el,j)=>c.pairs[j].right=el.value);const s=document.querySelector(`[data-source="${c.id}"]`),v=document.querySelector(`[data-verification="${c.id}"]`),n=document.querySelector(`[data-notes="${c.id}"]`);if(s)c.answer_source=s.value;if(v)c.verification=v.value;if(n)c.notes=n.value})}
function saveCurrent(){syncAllEditors();const idx=decks.findIndex(d=>d.id===currentDeck.id);if(idx>=0)decks[idx]=currentDeck;else decks.unshift(currentDeck);save();toastMsg('Deck saved.');setTimeout(()=>startSession(currentDeck.id,false),250)}
function exportCurrent(){syncAllEditors();const raw={format:'StudyCards',version:STUDYCARDS_VERSION,title:currentDeck.title,subject:currentDeck.subject,progress:currentDeck.progress,cards:currentDeck.cards.map(({id,type,question,choices,answer,pairs,answer_source,verification,notes})=>({id,type,question,choices,answer,pairs,answer_source,verification,notes}))};download(`${currentDeck.title.replace(/[^a-z0-9]+/gi,'-').toLowerCase()}.studyquest.json`,JSON.stringify(raw,null,2));toastMsg('✓ Deck exported. You can import it on another device.')}
function download(name,text){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'application/json'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}

function getActiveCards(){if(!currentDeck)return[];if(Array.isArray(activeCardIds))return activeCardIds.map(cid=>currentDeck.cards.find(c=>c.id===cid)).filter(Boolean);return currentDeck.cards}
function currentCard(){return getActiveCards()[studyIndex]}
function resetQuestionState(){flipped=false;quizAnswered=false;quizGiven=null;matchingSelections={}}
function startSession(id0,isQuiz){currentDeck=decks.find(d=>d.id===id0);if(!currentDeck)return;activeCardIds=null;studyIndex=0;resetQuestionState();quizMode=isQuiz;session={known:0,missed:0,results:{}};route=isQuiz?'quiz':'study';render()}
function startMissed(id0){const d=decks.find(x=>x.id===id0);if(!d)return;const ids=(d.progress?.missedIds||[]).filter(cid=>d.cards.some(c=>c.id===cid));if(!ids.length){toastMsg('There are no missed cards to review.');return}currentDeck=d;activeCardIds=ids;studyIndex=0;resetQuestionState();quizMode=false;session={known:0,missed:0,results:{}};route='study';render()}
function progressBar(){const total=getActiveCards().length||1;return `<div class="progress"><i style="width:${Math.min(100,(studyIndex/total)*100)}%"></i></div>`}

function studyPage(){if(!currentDeck)return nav('decks');const cards=getActiveCards();if(studyIndex>=cards.length)return finishPage(false);const c=currentCard();app.innerHTML=`<div class="shell study-wrap"><div class="mode-switch"><span>🧠 Study Mode${activeCardIds?` · Review Missed`:''}</span><button class="ghost" id="switchQuiz">Switch to Quiz</button></div><div class="study-card ${flipped?'flipped':''}" id="studyCard"><div class="card-face"><div class="pill">${studyIndex+1} / ${cards.length} · ${esc(c.type.replace('_',' '))}</div><div class="question"><h2>${esc(c.question)}</h2>${c.type==='multiple_choice'?`<p class="think-hint">Think of your answer before revealing it.</p>`:''}${c.type==='matching'?`<p class="think-hint">Think through each match before revealing the pairs.</p>`:''}<div class="actions"><button class="primary" id="flip">↻ Reveal Answer</button></div></div><div class="answer"><div class="eyebrow">Answer</div>${c.type==='matching'&&c.pairs?.length?`<div class="pair-table"><div class="pair-head"><span>Tribe / Region</span><span>Resource</span></div>${c.pairs.map(p=>`<div class="pair-row"><span>${esc(p.left)}</span><span>${esc(p.right)}</span></div>`).join('')}</div>`:`<h2>${esc(c.answer)}</h2>`}${c.answer_source==='inferred'?`<p class="answer-note">AI-inferred answer — verify against your worksheet.</p>`:''}<div class="study-controls"><button class="danger" id="miss">😕 Missed it</button><button class="primary" id="know">⭐ I knew it!</button></div></div></div>${progressBar()}<div class="study-controls"><button class="ghost" id="quit">Exit</button><button class="ghost" id="skip">Skip</button></div></div></div>`;document.getElementById('flip').onclick=()=>{flipped=true;render()};document.getElementById('know').onclick=()=>rate(true);document.getElementById('miss').onclick=()=>rate(false);document.getElementById('skip').onclick=()=>{advanceCard('study')};document.getElementById('quit').onclick=()=>nav('decks');document.getElementById('switchQuiz').onclick=()=>{quizMode=true;resetQuestionState();route='quiz';render()};animateIn()}

function quizPage(){if(!currentDeck)return nav('decks');const cards=getActiveCards();if(studyIndex>=cards.length)return finishPage(true);const c=currentCard();let body='';if(c.type==='multiple_choice'){body=`<div class="quiz-choices">${c.choices.map((x,i)=>{const selected=quizGiven===x;return `<button class="quiz-choice ${quizAnswered?(x===c.answer?'correct':''):selected?'selected':''}" data-choice="${i}" ${quizAnswered?'disabled':''}>${esc(x)}</button>`}).join('')}</div>`}else if(c.type==='true_false'){body=`<div class="quiz-choices"><button class="quiz-choice ${quizAnswered&&c.answer==='True'?'correct':''}" data-true="True" ${quizAnswered?'disabled':''}>True</button><button class="quiz-choice ${quizAnswered&&c.answer==='False'?'correct':''}" data-true="False" ${quizAnswered?'disabled':''}>False</button></div>`}else if(c.type==='matching'){body=matchingQuizBody(c)}else{body=`<textarea id="quizWritten" class="quiz-input" placeholder="Type your answer here…" ${quizAnswered?'disabled':''}>${esc(quizGiven||'')}</textarea><button class="primary" id="checkWritten" ${quizAnswered?'disabled':''}>Check Answer</button>`}
app.innerHTML=`<div class="shell study-wrap"><div class="mode-switch"><span>📝 Quiz Mode${activeCardIds?` · Review Missed`:''}</span><button class="ghost" id="switchStudy">Switch to Study</button></div><div class="quiz-card"><div class="pill">${studyIndex+1} / ${cards.length} · ${esc(c.type.replace('_',' '))}</div><h1>${esc(c.question)}</h1>${body}<div id="quizFeedback">${quizAnswered?quizFeedbackHtml(c):''}</div>${quizAnswered?`<div class="quiz-answer"><div class="eyebrow">Answer</div>${c.type==='matching'?matchingAnswerTable(c):`<h2>${esc(c.answer)}</h2>`}${c.answer_source==='inferred'?`<p class="answer-note">AI-inferred answer — verify against your worksheet.</p>`:''}<div class="study-controls"><button class="danger" id="quizMiss">😕 Need review</button><button class="primary" id="quizKnow">⭐ Got it!</button></div></div>`:''}</div>${progressBar()}<div class="study-controls"><button class="ghost" id="quit">Exit</button><button class="ghost" id="skip">Skip</button></div></div></div>`;wireQuiz(c);animateIn()}
function matchingQuizBody(c){const rights=shuffle(c.pairs.map(p=>p.right));return `<p class="think-hint">Choose a resource for each item. The choices are shuffled.</p><div class="matching-quiz">${c.pairs.map((p,i)=>`<div class="matching-question"><label>${esc(p.left)}</label><select data-match-left="${i}" ${quizAnswered?'disabled':''}><option value="">Choose a match…</option>${rights.map(r=>`<option value="${esc(r)}" ${matchingSelections[i]===r?'selected':''}>${esc(r)}</option>`).join('')}</select></div>`).join('')}</div><button class="primary" id="checkMatching" ${quizAnswered?'disabled':''}>Check Matches</button>`}
function matchingAnswerTable(c){return `<div class="pair-table">${c.pairs.map(p=>`<div class="pair-row"><span>${esc(p.left)}</span><span>${esc(p.right)}</span></div>`).join('')}</div>`}
function wireQuiz(c){document.getElementById('switchStudy').onclick=()=>{quizMode=false;resetQuestionState();route='study';render()};document.getElementById('quit').onclick=()=>nav('decks');document.getElementById('skip').onclick=()=>advanceCard('quiz');document.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>answerQuiz(c,c.choices[+b.dataset.choice]===c.answer,c.choices[+b.dataset.choice]));document.querySelectorAll('[data-true]').forEach(b=>b.onclick=()=>answerQuiz(c,b.dataset.true===c.answer,b.dataset.true));const cw=document.getElementById('checkWritten');if(cw)cw.onclick=()=>{const v=document.getElementById('quizWritten').value.trim();if(!v)return toastMsg('Type an answer first.');answerQuiz(c,roughMatch(v,c.answer),v)};const cm=document.getElementById('checkMatching');if(cm)cm.onclick=()=>{document.querySelectorAll('[data-match-left]').forEach(s=>matchingSelections[s.dataset.matchLeft]=s.value);if(Object.values(matchingSelections).some(v=>!v)||Object.keys(matchingSelections).length!==c.pairs.length){toastMsg('Choose a match for every item first.');return}const ok=c.pairs.every((p,i)=>matchingSelections[i]===p.right);answerQuiz(c,ok,'matching')};document.querySelectorAll('[data-match-left]').forEach(s=>s.onchange=()=>{matchingSelections[s.dataset.matchLeft]=s.value});if(quizAnswered){const know=document.getElementById('quizKnow'),miss=document.getElementById('quizMiss');if(know)know.onclick=()=>advanceCard('quiz',true);if(miss)miss.onclick=()=>advanceCard('quiz',false)}}
function roughMatch(a,b){const clean=x=>x.toLowerCase().replace(/[^a-z0-9 ]/g,'').trim();return clean(a)===clean(b)}
function quizFeedbackHtml(c){const ok=session.results[c.id];return `<div class="quiz-feedback ${ok?'good':'bad'}">${ok?'✓ Correct!':'Not quite.'}${c.type==='written'&&!ok&&quizGiven?`<span>Your response: ${esc(quizGiven)}</span>`:''}</div>`}
function answerQuiz(c,ok,given){if(quizAnswered)return;quizAnswered=true;quizGiven=given;session.results[c.id]=ok;render()}
function advanceCard(mode,rating){const c=currentCard();if(!c)return;if(mode==='quiz'&&typeof rating==='boolean'){session.results[c.id]=rating;rating?session.known++:session.missed++}else if(mode==='study'&&typeof rating==='boolean'){session.results[c.id]=rating;rating?session.known++:session.missed++}studyIndex++;resetQuestionState();route=mode==='quiz'?'quiz':'study';render()}
function rate(ok){advanceCard('study',ok)}

function finishPage(fromQuiz){const cards=getActiveCards();const total=cards.length;const resultKnown=cards.filter(c=>session.results[c.id]===true).length;const resultMissed=cards.filter(c=>session.results[c.id]===false).length;updateProgress();const reviewLabel=activeCardIds?'Review complete!':(fromQuiz?'Quiz complete!':'Amazing work!');app.innerHTML=`<div class="shell"><div class="panel center celebration" style="margin-top:80px"><div class="celebrate-burst">✦</div><div class="eyebrow">Quest complete</div><div class="big-score">${resultKnown}/${total}</div><h1>${reviewLabel}</h1><p class="muted">${resultMissed?`${resultMissed} card${resultMissed===1?'':'s'} need another look.`:'You mastered every card you rated!'}</p><div class="result-grid"><div><b>${resultKnown}</b><span>Known</span></div><div><b>${resultMissed}</b><span>Review</span></div><div><b>${total}</b><span>Cards</span></div></div><div class="actions" style="justify-content:center">${resultMissed&&!activeCardIds?`<button class="primary" id="reviewMissed">🔄 Review Missed</button>`:''}<button class="secondary" data-nav="decks">Back to My Decks</button></div></div></div>`;if(document.getElementById('reviewMissed'))document.getElementById('reviewMissed').onclick=()=>startMissed(currentDeck.id);animateIn();celebrate()}
function updateProgress(){const real=decks.find(d=>d.id===currentDeck.id);if(!real)return;real.progress=real.progress||{sessions:0,masteredIds:[],missedIds:[]};real.progress.sessions++;const mastered=new Set(real.progress.masteredIds||[]),missed=new Set(real.progress.missedIds||[]);Object.entries(session.results).forEach(([cid,ok])=>{if(ok){mastered.add(cid);missed.delete(cid)}else{missed.add(cid);mastered.delete(cid)}});real.progress.masteredIds=[...mastered];real.progress.missedIds=[...missed];save()}
function celebrate(){if(!window.gsap)return;gsap.from('.celebrate-burst',{scale:0,rotation:-120,duration:.8,ease:'back.out(2)'});gsap.to('.celebrate-burst',{rotation:360,duration:2.5,repeat:-1,ease:'none'})}
function shuffle(a){const out=[...a];for(let i=out.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[out[i],out[j]]=[out[j],out[i]]}return out}
function animateIn(){if(window.gsap)gsap.from('#app .panel,#app .deck-card,#app .hero > *',{opacity:0,y:14,stagger:.04,duration:.45,ease:'power2.out'})}
async function copyTemplate(){let t='';try{const r=await fetch('templates/chatgpt-import-template.md',{cache:'no-store'});if(!r.ok)throw Error('template fetch failed');t=await r.text()}catch{toastMsg('Could not load the import template. Please refresh and try again.');return}try{if(navigator.clipboard?.writeText){await navigator.clipboard.writeText(t);toastMsg('✓ Template copied — paste it into ChatGPT with your test photos.');return}}catch{}try{const ta=document.createElement('textarea');ta.value=t;ta.setAttribute('readonly','');ta.style.position='fixed';ta.style.opacity='0';document.body.appendChild(ta);ta.select();const ok=document.execCommand('copy');ta.remove();if(ok){toastMsg('✓ Template copied — paste it into ChatGPT with your test photos.');return}}catch{}const modal=document.getElementById('templateFallback'),box=document.getElementById('templateText');if(modal&&box){box.value=t;modal.hidden=false;setTimeout(()=>{box.focus();box.select()},50)}else toastMsg('Please open the template file and copy its text manually.')}

const cv=document.getElementById('space'),ctx=cv.getContext('2d');let dots=[];function resize(){cv.width=innerWidth*devicePixelRatio;cv.height=innerHeight*devicePixelRatio;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);dots=Array.from({length:Math.min(90,Math.floor(innerWidth/15))},()=>({x:Math.random()*innerWidth,y:Math.random()*innerHeight,r:Math.random()*1.4+.3,v:Math.random()*.15+.03}))}function particles(){ctx.clearRect(0,0,innerWidth,innerHeight);ctx.fillStyle='rgba(255,255,255,.45)';dots.forEach(d=>{d.y-=d.v;if(d.y<0)d.y=innerHeight;ctx.beginPath();ctx.arc(d.x,d.y,d.r,0,Math.PI*2);ctx.fill()});requestAnimationFrame(particles)}addEventListener('resize',resize);resize();particles();render();
